apiVersion: v1
kind: Service
metadata:
  name: {{ include "cosmoguard.fullname" . }}
  labels: {{- include "cosmoguard.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "cosmoguard.selectorLabels" . | nindent 4 }}
  ports:
    - name: lcd
      port: {{ .Values.service.lcdPort }}
      targetPort: lcd
      protocol: TCP
    - name: rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: rpc
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
    {{- if .Values.config.enableEvm }}
    - name: evm-rpc
      port: {{ .Values.service.evmRpcPort | default .Values.config.evmRpcPort }}
      targetPort: evm-rpc
      protocol: TCP
    - name: evm-rpc-ws
      port: {{ .Values.service.evmRpcWsPort | default .Values.config.evmRpcWsPort }}
      targetPort: evm-rpc-ws
      protocol: TCP
    {{- end }}
    {{- if .Values.config.metrics.enable }}
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
    {{- if .Values.config.dashboard.enable }}
    - name: dashboard
      port: {{ .Values.service.dashboardPort | default .Values.config.dashboard.port }}
      targetPort: dashboard
      protocol: TCP
    {{- end }}
